import {NextResponse} from 'next/server';
import {z} from 'zod';
import {database,snapshot,identity,operationStatement} from '@/lib/server';
import {prepare,kitchen,today,roleLabels,type Op,type Product} from '@/lib/domain';
import catalog from '@/lib/catalog.json';
export const dynamic='force-dynamic';
const draft=z.object({id:z.string().uuid(),type:z.string().max(40),date:z.string().max(10),destination:z.string().max(100),reference:z.string().max(80),supplier:z.string().max(200),notes:z.string().max(1000),lines:z.array(z.object({code:z.string().max(30),quantity:z.number().finite(),price:z.number().finite()})).max(40)});
const response=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
function error(e:unknown){const m=e instanceof Error?e.message:String(e);if(m==='AUTH')return response({error:'Inicia sesión para continuar.',auth:true},401);if(m==='MEMBERSHIP')return response({error:'Tu cuenta aún no tiene acceso. Pide al administrador que te agregue en Equipo.'},403);if(e instanceof z.ZodError)return response({error:'Revisa los campos del formulario: '+e.issues[0].path.join('.')},400);if(/UNIQUE constraint failed: operations\.(seq|id)/i.test(m))return response({error:'Otra persona acaba de guardar. Actualiza los datos y vuelve a intentar; tu captura sigue en pantalla.'},409);if(/D1_|SQLITE|binding|database|no such table/i.test(m)){console.error('Abasto storage error',m);return response({error:'No se pudo acceder al registro. Tu captura se conserva; intenta nuevamente.'},503);}return response({error:m},400);}
export async function GET(){try{const s=await snapshot(),u=await identity(s);const dest=kitchen(u.role);if(dest){s.operations=s.operations.filter(o=>o.destination===dest&&['Solicitud cocina','Traspaso','Devolución cocina'].includes(o.type));const ids=new Set(s.operations.map(o=>o.seq));s.lines=s.lines.filter(l=>ids.has(l.seq)).map(l=>({...l,price:0,value:0}));s.products=s.products.map(p=>({...p,price:0,presentationPrice:0,usableCost:0,supplier:'',notes:'',minimum:0,maximum:0}));s.openings=[];}if(u.role!=='admin')s.members=[];return response({...s,user:{name:u.name,email:u.email,role:u.role},initialized:s.products.length>0});}catch(e){return error(e);}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Abre el formulario desde la aplicación.'},403);
 if(!req.headers.get('content-type')?.startsWith('application/json'))return response({error:'Formato de solicitud inválido.'},415);
 const body=z.record(z.unknown()).parse(await req.json());const s=await snapshot(),u=await identity(s),db=database();
 const id=z.string().uuid().parse(body.id);const previous=s.operations.find(o=>o.id===id);if(previous){if(previous.actorId!==u.userId)return response({error:'La solicitud pertenece a otra cuenta.'},403);return response({folio:previous.folio,repeated:true});}
 const seq=(s.operations.at(-1)?.seq??0)+1;const timestamp=new Date().toISOString();const o:Op={seq,id,folio:'ADM-'+String(seq).padStart(7,'0'),type:'Configuración',date:today(),destination:'Almacén',reference:'',supplier:'',notes:'',actor:u.name,actorId:u.userId,timestamp};
 const statements=[];
 if(body.action==='initialize'){
  if(u.role!=='admin')throw new Error('Sólo Administración puede iniciar el catálogo.');if(s.products.length)throw new Error('El catálogo ya está iniciado.');o.notes='Importación del catálogo final: 310 productos, sin movimientos de prueba.';
  statements.push(operationStatement(o));for(const p of catalog)statements.push(db.prepare('INSERT INTO products (code,data) VALUES (?,?)').bind(p.code,JSON.stringify(p)));
 }else if(body.action==='member'){
  if(u.role!=='admin')throw new Error('Sólo Administración puede gestionar accesos.');const member=z.object({email:z.string().email().max(200),name:z.string().min(2).max(100),role:z.enum(['almacen','compras','cocina_mv','cocina_cc','admin','disabled'])}).parse(body.member);member.email=member.email.toLowerCase();if(member.email===u.email)throw new Error('No puedes cambiar tu propio acceso desde aquí.');o.type='Equipo';o.notes=member.email+' · '+member.role;statements.push(operationStatement(o),db.prepare('INSERT INTO members (email,role,name) VALUES (?,?,?) ON CONFLICT(email) DO UPDATE SET role=excluded.role,name=excluded.name').bind(member.email,member.role,member.name));
 }else if(body.action==='product'){
  if(u.role!=='admin')throw new Error('Sólo Administración puede cambiar el catálogo.');const p=z.object({code:z.string().min(1).max(30),minimum:z.number().min(0).max(1e9),maximum:z.number().min(0).max(1e9),price:z.number().positive().max(1e7),supplier:z.string().max(200),active:z.boolean()}).parse(body.product);if(p.maximum<p.minimum)throw new Error('El máximo debe ser mayor o igual al mínimo.');const old=s.products.find(x=>x.code===p.code);if(!old)throw new Error('No se encontró el producto.');const updated:Product={...old,...p,presentationPrice:p.price*old.presentation,usableCost:old.yieldRate>0?p.price/old.yieldRate:old.usableCost};o.type='Catálogo';o.notes=JSON.stringify({code:p.code,anterior:old,nuevo:updated});statements.push(operationStatement(o),db.prepare('UPDATE products SET data=? WHERE code=?').bind(JSON.stringify(updated),p.code));
 }else if(body.action==='register'){
  if(!s.products.length)throw new Error('Administración debe importar el catálogo antes de registrar.');const d=draft.parse(body);const prepared=prepare(s,d,u.role);Object.assign(o,{type:d.type,date:d.date,destination:d.destination,reference:d.reference,supplier:d.supplier,notes:d.notes});const prefix=d.type==='Pedido de compra'?'COM':d.type==='Solicitud cocina'?'SOL':'MOV';o.folio=prefix+'-'+d.date.slice(0,4)+'-'+String(seq).padStart(7,'0');statements.push(operationStatement(o));for(const l of prepared){statements.push(db.prepare('INSERT INTO lines (seq,code,quantity,price,delta,value) VALUES (?,?,?,?,?,?)').bind(seq,l.code,l.quantity,l.price,l.delta,l.value));if(d.type==='Apertura')statements.push(db.prepare('INSERT INTO openings (code,seq) VALUES (?,?)').bind(l.code,seq));}
 }else throw new Error('Selecciona una acción válida.');
 const member=s.members.find(m=>m.email===u.email);if(member&&!member.userId)statements.push(db.prepare('UPDATE members SET user_id=? WHERE email=? AND user_id IS NULL').bind(u.userId,u.email));
 await db.batch(statements);return response({folio:o.folio});
 }catch(e){return error(e);}}
